export { getPopular } from "./get-popular";
export  { getTrending } from "./get-popular-anime-this-season";
export { getAnime } from "./get-anime-detail";
export { getPopularAiring } from "./get-popular-airing";
export { getAnimeSearch } from "./get-anime-by-search";
export { getStudios } from "./get-studios";
export { getStudio } from "./get-studio-detail";
export { getMangas } from "./get-manga";
export { getManga } from "./get-manga-detail";